blank_issues_enabled: true
contact_links:
  - name: Discuss adding a new Feature
    url: https://github.com/EddieDover/Theater-of-the-Mind/discussions/categories/ideas
    about: Please use this link to discuss adding a new feature.
